name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest fastapi uvicorn python-dotenv pydantic-settings \
            google-api-python-client google-auth-httplib2 google-auth-oauthlib \
            sqlalchemy chromadb 'spacy>=3.8.0,<3.9.0' sentence-transformers

      - name: Ruff
        run: ruff .

      - name: MyPy
        run: mypy backend

      - name: PyTest
        run: pytest -q
